### ISSUE TITLE
The first IF models and a correction

### ISSUE THREAD

**Issue by sharbatc** [TomDonoghue/NeuroHistory#1]
Perhaps you could include Louis Lapicque's first introduction of an IF like model (1907) (https://link.springer.com/content/pdf/10.1007%2Fs00422-007-0190-0.pdf) - you would understand the original in French as well I guess.

Also, Haldane is spelt wrong in Haldana, On Being the Right Size.

**Comment by TomDonoghue** [comment]
Thanks! Added & fixed!
